<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ingrediente;

class IngredienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ingrediente::Truncate();

        # Especias
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='sal';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimienta';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimienta negra';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimienta verde';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimienta blanca';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimienta rosa';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pimenton';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='oregano';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='azucar';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='comino';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='azucar impalpable';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='sal del Himalaya';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aji molido';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='curry';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='jengibre';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='ajo';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='curcuma';
        $ingrediente->tipo='especia';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Verduras y frutas
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='zapallo';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='papa';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='batata';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='zanahoria';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cebolla';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cebolla morada';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cebolla de verdeo';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='morron colorado';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='morron amarillo';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='morron verde';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='apio';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='puerro';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aji vinagre';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aji picante';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='lechuga';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='tomate';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='tomate redondo';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='tomate perita';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='lechuga mantecosa';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='repollo';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='manzana';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='manzana roja';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='manzana verde';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='naranja';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='limon';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='banana';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='platano';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pomelo';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='frutilla';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cereza';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='kiwi';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pepino';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='sandia';
        $ingrediente->tipo='fruta';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='choclo';
        $ingrediente->tipo='verdura';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Carne de pollo
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pechuga de pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='pata de pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='ala de pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='rancho de pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='huesos de pollo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Carne de cerdo
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='bondiola de cerdo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='chuleta de cerdo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='panceta';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='panceta ahumada';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='panceta salada';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Carne de vaca
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='osobuco';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='paleta de vaca';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='bife angosto';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='bife ancho';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aguja';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='ojo de bife';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='asado de vaca';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='vacio';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='bola de lomo';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='nalga de vaca';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cuadril';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='falda';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='carne de vaca';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='matambre de vaca';
        $ingrediente->tipo='carne';
        $ingrediente->isVisible=true;
        $ingrediente->save();


        # Embutidos, fiambres y productos de origen animal
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='salchicha';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='chorizo';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='salchicha parrillera';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='longaniza';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='fiambrin';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='queso';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='jamon cocido';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='jamon crudo';
        $ingrediente->tipo='fiambre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='queso cheddar';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='queso parmesano';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='queso reggianito';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='queso gouda';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='leche';
        $ingrediente->tipo='lacteo';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Aceites
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aceite de oliva';
        $ingrediente->tipo='aceite';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aceite neutro';
        $ingrediente->tipo='aceite';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aceite de girasol';
        $ingrediente->tipo='aceite';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aceite de coco';
        $ingrediente->tipo='aceite';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='aceite de soja';
        $ingrediente->tipo='aceite';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Legumbres
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='poroto';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='lenteja';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='garbanzo';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='mani';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='nuez';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='arveja';
        $ingrediente->tipo='legumbre';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Alcohol
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='vino blanco';
        $ingrediente->tipo='alcohol';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='vino tinto';
        $ingrediente->tipo='alcohol';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='cerveza';
        $ingrediente->tipo='alcohol';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Harinas
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='harina';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='harina de trigo';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='harina de maiz';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='maicena';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='polenta';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='harina 0000';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='harina 000';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Fideos y arroces
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='arroz';
        $ingrediente->tipo='arroz';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='fideos';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='fideos soperos';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='fideos de arroz';
        $ingrediente->tipo='harina';
        $ingrediente->isVisible=true;
        $ingrediente->save();
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='arroz yamani';
        $ingrediente->tipo='arroz';
        $ingrediente->isVisible=true;
        $ingrediente->save();

        # Sin categoria
        $ingrediente = new Ingrediente;
        $ingrediente->nombre='leche de coco';
        $ingrediente->tipo='otro';
        $ingrediente->isVisible=true;
        $ingrediente->save();
    }
}
